name: ZTI
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - streamlit==1.56.0
      - bcrypt==4.2.1
      - requests
      - sqlalchemy
      - pyodbc
      - extra-streamlit-components
      - folium
      - streamlit-folium
      - geopy